
<div class="prInner">
    <h2>{t}{tparam value=$SITE_NAME_AS_DOMAIN}%s Services Agreement{/t}</h2>
    <p class="prInnerTop">{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_DOMAIN}This Agreement governs your use of %s, LLC's community organizing and website publishing services developed, operated, and maintained by %s, accessible via %s or another designated web site or IP address, or ancillary online or offline products and services components (collectively, the &quot;Service&quot;).  If you are entering into this Agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity to these terms and conditions, in which case the terms &quot;you&quot; or &quot;your&quot; shall refer to such entity.{/t}</p>
    <ol class="prInnerTop prIndentLeftLarge">
        <li>
            <h4>{t}License Grant{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}%s hereby grants you a non-exclusive, non-transferable, worldwide right to use the Service subject to the terms and conditions of this Agreement. All rights not expressly granted to you are reserved by %s and its licensors.{/t}</p>
        </li>
        <li>
            <h4>{t}Restrictions on Use{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}You may not access the Service if you are a direct competitor of %s, except with %s's prior written consent. In addition, you may not access the Service for purposes of monitoring its availability, performance or functionality, or for any other benchmarking or competitive purposes.{/t}</p>
			<p>{t}You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or the content in any way; (ii) modify or make derivative works based upon the Service or the content; (iii) create Internet"links" to the Service or"frame" or"mirror" any content on any other server or wireless or Internet-based device; or (iv) reverse engineer or access the Service in order to (a) build a competitive product or service, (b) build a product using similar ideas, features, functions or graphics of the Service, or (c) copy any ideas, features, functions or graphics of the Service.{/t}</p>
			<p>{t}You may use the Service only for your internal business purposes and shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Service or the data contained therein; or (v) attempt to gain unauthorized access to the Service or its related systems or networks. {/t}</p>
        </li>
        <li>
            <h4>{t}Your Responsibilities{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}You are responsible for all activity occurring under your User accounts and shall abide by all applicable local, state, national and foreign laws, treaties and regulations in connection with your use of the Service, including those related to data privacy, international communications and the transmission of technical or personal data. You shall: (a) notify %s immediately of any unauthorized use of any password or account or any other known or suspected breach of security; (b) report to %s immediately and use reasonable efforts to stop immediately any copying or distribution of content that is known or suspected by you or your Users; and (c) not impersonate another %s user or provide false identity information to gain access to or use the Service.{/t}</p>
        </li>
        <li>
            <h4>{t}User-Submitted Content{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_DOMAIN}{tparam value=$SITE_NAME_AS_DOMAIN}{tparam value=$SITE_NAME_AS_DOMAIN}{tparam value=$SITE_NAME_AS_DOMAIN}In the course of interacting with the Service, users of the service may submit various kinds of content to %s, or access various kinds of content from other websites for display on %s, such as words, events, photos, profile photos, documents, lists, videos, and other types of media. You acknowledge that this content may be displayed by %s and that %s may use and display this content freely under the GNU Free Documentation License.{/t}</p>
        </li>
        <li>
            <h4>{t}Privacy &amp; Security; Disclosure{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_DOMAIN}{tparam value=$LOCALE}{tparam value=$SITE_NAME_AS_STRING}%s's privacy and security policies may be viewed at %s/%s/info/privacy/.  %s reserves the right to modify its privacy and security policies in its reasonable discretion from time to time.{/t}</p>
        </li>
        <li>
            <h4>{t}Intellectual Property Ownership{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}%s alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to the %s technology (including software, hardware, products, processes, algorithms, user interfaces, know-how, techniques, designs and other tangible or intangible technical material or information), the content and the service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Service. The %s name, logo and the product names associated with the Service are trademarks of %s or third parties, and no right or license is granted to use them.{/t}</p>
        </li>
        <li>
            <h4>{t}Third Party Interactions{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}During use of the Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of advertisers or sponsors showing their goods and/or services through the Service. Any such activity, and any terms, conditions, warranties or representations associated with such activity, is solely between you and the applicable third-party. %s and its licensors shall have no liability, obligation or responsibility for any such correspondence, purchase or promotion between you and any such third-party. %s does not endorse any sites on the Internet that are linked through the Service. %s provides these links to you only as a matter of convenience, and in no event shall %s or its licensors be responsible for any content, products, or other materials on or available from such sites. %s provides the Service to you pursuant to the terms and conditions of this Agreement. You recognize, however, that certain third-party providers of ancillary software, hardware or services may require your agreement to additional or different license or other terms prior to your use of or access to such software, hardware or services.{/t}</p>
        </li>
        <li>
            <h4>{t}Monthly License Fee{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}You shall pay all fees or charges to your account in accordance with the fees, charges, and billing terms in effect at the time a fee or charge is due and payable.  %s reserves the right to suspend or terminate this Agreement and your access to the Service if your account becomes delinquent. Delinquent accounts are subject to interest of 1.0&#37; per month on any outstanding balance, or the maximum permitted by law, whichever is less, plus all expenses of collection. You will continue to be charged for User licenses during any period of suspension. If you or %s initiates termination of this Agreement, you will be obligated to pay the balance due on your account computed in accordance with the Charges and Payment of Fees section above. You agree that %s may charge such unpaid fees to your credit card or otherwise bill you for such unpaid fees.  %s reserves the right to impose a reconnection fee in the event you are suspended and thereafter request access to the Service.{/t}</p>
        </li>
        <li>
            <h4>{t}Term{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}This Agreement commences on the Effective Date. The Initial Term will be as you elect during the online subscription process or as otherwise mutually agreed upon, commencing on the date you agree to pay for the Service by completing the online subscription form or otherwise. Upon the expiration of the Initial Term, this Agreement will automatically renew for successive renewal terms equal in duration to the Initial Term (or one year, if the Initial Term is greater than one year) at %s's then-current fees. {/t}</p>
        </li>
        <li>
            <h4>{t}Termination{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}Either party may terminate this Agreement, effective only upon the expiration of the then current License Term, by notifying the other party in writing at least five (5) business days prior to the date of the invoice for the following term. In the case of free trials, notifications provided through the Service indicating the remaining number of days in the free trial shall constitute notice of termination. You agree and acknowledge that %s has no obligation to retain customer data, and may delete such data after termination.  %s may, in its sole discretion, terminate your password, account or use of the Service if you breach or otherwise fail to comply with this Agreement. In addition, %s may terminate a free account at any time in its sole discretion.{/t}</p>
        </li>
        <li>
            <h4>{t}Representations &amp; Warranties{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}Each party represents and warrants that it has the legal power and authority to enter into this Agreement. %s represents and warrants that it will provide the Service in a manner consistent with general industry standards reasonably applicable to the provision thereof and that the Service will perform substantially in accordance with the online %s help documentation under normal use and circumstances. You represent and warrant that you have not falsely identified yourself nor provided any false information to gain access to the Service and that your billing information is correct.{/t}</p>
        </li>
        <li>
            <h4>{t}Mutual Indemnification{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}You shall indemnify and hold %s, its licensors and each such party's parent organizations, subsidiaries, affiliates, officers, directors, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (i) a claim alleging that use of the Customer Data infringes the rights of, or has caused harm to, a third party; (ii) a claim, which if true, would constitute a violation by you of your representations and warranties; or (iii) a claim arising from the breach by you or your Users of this Agreement, provided in any such case that %s (a) gives written notice of the claim promptly to you; (b) gives you sole control of the defense and settlement of the claim (provided that you may not settle or defend any claim unless you unconditionally release %s of all liability and such settlement does not affect %s's business or Service); (c) provides to you all available information and assistance; and (d) has not compromised or settled such claim.{/t}</p>
			<p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}%s shall indemnify and hold you and your parent organizations, subsidiaries, affiliates, officers, directors, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (i) a claim alleging that the Service directly infringes a copyright, a U.S. patent issued as of the Effective Date, or a trademark of a third party; (ii) a claim, which if true, would constitute a violation by %s of its representations or warranties; or (iii) a claim arising from breach of this Agreement by %s; provided that you (a) promptly give written notice of the claim to %s; (b) give %s sole control of the defense and settlement of the claim (provided that %s may not settle or defend any claim unless it unconditionally releases you of all liability); (c) provide to %s all available information and assistance; and (d) have not compromised or settled such claim. %s shall have no indemnification obligation, and you shall indemnify %s pursuant to this Agreement, for claims arising from any infringement arising from the combination of the Service with any of your products, service, hardware or business process(s).{/t}</p>
        </li>
        <li>
            <h4>{t}Disclaimer of Warranties{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING|upper}{tparam value=$SITE_NAME_AS_STRING|upper}{tparam value=$SITE_NAME_AS_STRING|upper}%s AND ITS LICENSORS MAKE NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, TRUTH, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICE OR ANY CONTENT. %s AND ITS LICENSORS DO NOT REPRESENT OR WARRANT THAT (A) THE USE OF THE SERVICE WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA, (B) THE SERVICE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (C) ANY STORED DATA WILL BE ACCURATE OR RELIABLE, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (E) ERRORS OR DEFECTS WILL BE CORRECTED, OR (F) THE SERVICE OR THE SERVER(S) THAT MAKE THE SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE SERVICE AND ALL CONTENT IS PROVIDED TO YOU STRICTLY ON AN"AS IS" BASIS. ALL CONDITIONS, REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS, ARE HEREBY DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW BY %s AND ITS LICENSORS.{/t}</p>
        </li>
        <li>
            <h4>{t}Internet Delays{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING|upper}%s'S SERVICES MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. {$SITE_NAME_AS_STRING|upper} IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS.{/t}</p>
        </li>
		<li>
            <h4>{t}Limitation of Liability{/t}</h4>
            <p>{t}IN NO EVENT SHALL EITHER PARTY'S AGGREGATE LIABILITY EXCEED THE AMOUNTS ACTUALLY PAID BY AND/OR DUE FROM YOU IN THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM. IN NO EVENT SHALL EITHER PARTY AND/OR ITS LICENSORS BE LIABLE TO ANYONE FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND (INCLUDING LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THIS SERVICE, INCLUDING BUT NOT LIMITED TO THE USE OR INABILITY TO USE THE SERVICE, OR FOR ANY CONTENT OBTAINED FROM OR THROUGH THE SERVICE, ANY INTERRUPTION, INACCURACY, ERROR OR OMISSION, REGARDLESS OF CAUSE IN THE CONTENT, EVEN IF THE PARTY FROM WHICH DAMAGES ARE BEING SOUGHT OR SUCH PARTY'S LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.{/t}</p>
        </li>
		<li>
            <h4>{t}Additional Rights{/t}</h4>
            <p>{t}Certain states and/or jurisdictions do not allow the exclusion of implied warranties or limitation of liability for incidental, consequential or certain other types of damages, so the exclusions set forth above may not apply to you.{/t}</p>
        </li>
		<li>
            <h4>{t}Local Laws and Export Control{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}%s and its licensors make no representation that the Service is appropriate or available for use in other locations. If you use the Service from outside the United States of America, you are solely responsible for compliance with all applicable laws, including without limitation export and import regulations of other countries.   This site provides services and uses software and technology that may be subject to United States export controls administered by the U.S. Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control, and other U.S. agencies. By using the Service, you represent and warrant that you are not located in, under the control of, or a national or resident of an Embargoed Country or Designated National. You agree to comply strictly with all U.S. export laws and assume sole responsibility for obtaining licenses to export or re-export as may be required. {/t}</p>
        </li>
		<li>
            <h4>{t}Notice{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}%s may give notice by means of a general notice on the Service, electronic mail to your e-mail address on record in %s's account information, or by written communication sent by first class mail or pre-paid post to your address on record in %s's account information. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email). You may give notice to %s (such notice shall be deemed given when received by %s) at any time by any of the following: letter sent by confirmed facsimile to %s at the following fax number: 612-573-6488; letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail to %s at the following addresses (whichever is appropriate): %s, inc., 3611 Farmington Road
Minnetonka, MN 55305  addressd to the attention of: Chief Financial Officer.{/t}</p>
        </li>
		<li>
            <h4>{t}Assignment; Change in Control{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}This Agreement may not be assigned by you without the prior written approval of %s but may be assigned without your consent by %s to (i) a parent or subsidiary, (ii) an acquirer of assets, or (iii) a successor by merger. Any purported assignment in violation of this section shall be void. Any actual or proposed change in control of you that results or would result in a direct competitor of %s directly or indirectly owning or controlling 50&#37; or more of you shall entitle %s to terminate this Agreement for cause immediately upon written notice.{/t}</p>
        </li>
		<li>
            <h4>{t}General{/t}</h4>
            <p>{t}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_STRING}{tparam value=$SITE_NAME_AS_DOMAIN}{tparam value=$SITE_NAME_AS_STRING}This Agreement shall be governed by Minnesota law and controlling United States federal law, without regard to the choice or conflicts of law provisions of any jurisdiction, and any disputes, actions, claims or causes of action arising out of or in connection with this Agreement or the Service shall be subject to the exclusive jurisdiction of the state and federal courts located in Minneapolis, Minnesota. No joint venture, partnership, employment, or agency relationship exists between you and %s as a result of this Agreement or use of the Service. The failure of %s to enforce any right or provision in this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by %s in writing. This Agreement and any materials available on the %s website specifically incorporated by reference herein, comprise the entire agreement between you and %s and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, between the parties regarding the subject matter contained herein.{/t}</p>
        </li>
    </ol>
</div>
