<!-- content object setting -->

<ul class="prCO-settings">
	<li><a href="#null" onclick="var _tmpLine=WarecorpDDblockApp.getElementBorderStyle('{$cloneId}'); showAKLinePicker('{$cloneId}LP1', _tmpLine, getElementPosition(this)[0], getElementPosition(this)[1] + 30, 'WarecorpDDblockApp.setElementBorderStyle(\'{$cloneId}\', \'#\')');"><span onmouseover="this.style.border='1px solid #0A246A'" onmouseout="this.style.border='1px solid #F0F0EE'" style="display:block; border:1px solid #F0F0EE;"><img src="{$AppTheme->images}/decorators/hr.gif"/><img src="{$AppTheme->images}/decorators/button_menu.gif"/></span></a></li>
	<li><a href="#null" onclick="var _tmpColor=WarecorpDDblockApp.getElementBorderColor('{$cloneId}'); showAKColorPickerMCEStyle('{$cloneId}CP2', _tmpColor, getElementPosition(this)[0], getElementPosition(this)[1] + 30, 'WarecorpDDblockApp.setElementBorderColor(\'{$cloneId}\', \'#\')');"><div id="{$cloneId}CP2_indicator" style="position:absolute; width: 17px; height: 4px; margin-top: 13px; font-size:0px;  margin-left:2px; "></div><span onmouseover="this.style.border='1px solid #0A246A'" onmouseout="this.style.border='1px solid #F0F0EE'" style="display:block; border:1px solid #F0F0EE;"><img src="{$AppTheme->images}/decorators/ln.gif"/><img src="{$AppTheme->images}/decorators/button_menu.gif"/></span></a></li>
    <li><a href="#null" onclick="var _tmpColor=WarecorpDDblockApp.getElementBackgroundColor('{$cloneId}'); showAKColorPickerMCEStyle('{$cloneId}CP1', _tmpColor, getElementPosition(this)[0], getElementPosition(this)[1] + 30, 'WarecorpDDblockApp.setElementBackgroundColor(\'{$cloneId}\', \'#\')');"><div id="{$cloneId}CP1_indicator" style="position:absolute; width: 17px; height: 4px; margin-top: 13px; font-size:0px;  margin-left:2px; "></div><span onmouseover="this.style.border='1px solid #0A246A'" onmouseout="this.style.border='1px solid #F0F0EE'" style="display:block; border:1px solid #F0F0EE;"><img src="{$AppTheme->images}/decorators/backcolor.gif"/><img src="{$AppTheme->images}/decorators/button_menu.gif"/></span></a></li>
    <li><a href="#null" onclick="WarecorpDDblockApp.resetElementStyle('{$cloneId}');return false;"><span onmouseover="this.style.border='1px solid #0A246A'" onmouseout="this.style.border='1px solid #F0F0EE'" style="display:block; border:1px solid #F0F0EE;"><img src="{$AppTheme->images}/decorators/removeformat.gif"/></span></a></li>
</ul>
<!-- /content object setting -->
